stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - data/heart.csv
      - preprocess.py
    outs:
      - data/train.csv
      - data/test.csv

  train:
    cmd: python train.py
    deps:
      - data/train.csv
      - train.py
    outs:
      - models/model.pkl
  tune:
    cmd: python tune.py
    deps:
      - data/train.csv
      - tune.py
    outs:
      - models_tuned/model.pkl  

  validate:
    cmd: python validate.py
    deps:
      - data/test.csv
      - models_tuned/model.pkl
      - validate.py
    metrics:
      - models/metrics.json
    plots:
      - models/confusion_matrix.png
